### ISSUE TITLE
If the language wasn't detected correctly, use a language from the same alphabet

### ISSUE THREAD

**Issue by DevAlone** [bond95/ToxicBot#2]
`whatlang` library sometimes detects incorrect language with the same or similar alphabet, for example russian|belorussian|ukrainian or english|czech|slovak. So in case when we don't have data for the detected language, we can use messages from a language with the same alphabet using `script` field of `whatlang`, instead of just a random language.

**Comment by bond95** [comment]
@DevAlone I think it's already fixed
